disabled_rules:
  - type_body_length
  - line_length
  - identifier_name
  - trailing_whitespace
  - colon
  - unused_closure_parameter
  - file_length
  - function_body_length
  - multiple_closures_with_trailing_closure
  - cyclomatic_complexity
  - for_where
  - vertical_whitespace
  - implicit_optional_initialization
  - large_tuple
  - non_optional_string_data_conversion
  - redundant_string_enum_value

excluded:
  - Darwin/
  - Android/
  - .build/
